version: '3'
services:  
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    network_mode: host
    environment:
      - DOMAIN=${NGINX_DOMAIN}
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    expose:
      - "80"
      - "443"
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./templates:/etc/nginx/templates