version: '3.8'
services:
  nginx_pm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx_pm
    restart: always
    network_mode: host
    expose:
      - "80"
      - "81"
      - "443"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt