version: '3'
services:
  postgresql:
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_DB=confluence
      - POSTGRES_USER=confluence
      - POSTGRES_PASSWORD=confluence
    expose:
      - "5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data

  confluence-server:
    image: atlassian/confluence:8.8.0
    restart: always
    environment:
      - ATL_PROXY_NAME=wiki.vdbogdanov.ru
      - ATL_PROXY_PORT=443
      - ATL_TOMCAT_SCHEME=https
      - ATL_JDBC_URL=jdbc:postgresql://postgresql:5432/confluence
      - ATL_JDBC_USER=confluence
      - ATL_JDBC_PASSWORD=confluence
      - ATL_DB_TYPE=postgresql
    ports:
      - "127.0.0.1:8090:8090"
      - "127.0.0.1:8091:8091"
    volumes:
      - ./data/config:/var/atlassian/application-data/confluence
    depends_on:
      - postgresql