version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: marzban_db
    restart: always
    env_file: .env
    network_mode: host
    environment:
      MYSQL_DATABASE: marzban
    command: --bind-address=127.0.0.1 --mysqlx-bind-address=127.0.0.1
    expose:
      - "33060"
      - "3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: marzban_phpmyadmin
    restart: always
    env_file: .env
    network_mode: host
    environment:
      PMA_HOST: 127.0.0.1
      APACHE_PORT: 8010
    expose:
      - "8010"
    depends_on:
      - mysql

  marzban:
    image: gozargah/marzban:latest
    container_name: marzban
    restart: always
    env_file: .env
    network_mode: host
    expose:
      - "8000/tcp"
      - "8080/tcp"
      - "8081/tcp"
      - "8443/tcp"
      - "2053/tcp"
      - "2083/tcp"
      - "1080/tcp"
      - "1080/udp"
    volumes:
      - ./data:/var/lib/marzban
    depends_on:
      - mysql