version: '3'
services:  
  nginx:
    image: nginx
    restart: always
    container_name: nginx
    network_mode: host
    environment:
      - DOMAIN=${NGINX_DOMAIN}
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./templates:/etc/nginx/templates