version: '3.8'
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    container_name: nginx_pm
    network_mode: host
    expose:
      - "80"
      - "81"
      - "443"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt