version: "3.8"
services:
  app:
    image: "jc21/nginx-proxy-manager:latest"
    network_mode: "host"
    restart: unless-stopped
    expose:
      - "80"
      - "81"
      - "443"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt